# NumPy Exercise - 1

In [5]:
import numpy as np

a = np.arange(15).reshape(3,5)

a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Attribute# 1: The dimensions of the array

In [6]:
a.shape

(3, 5)

Attribute# 2: The number of axes (dimensions) of the array

In [7]:
a.ndim

2

Attribute# 3: An object describing the type of the elements in the array

In [9]:
a.dtype.name

'int32'

Attribute# 4: The size in bytes of each element of the array

In [11]:
a.itemsize

4

Attribute# 5: The total number of elements of the array

In [12]:
a.size

15

Attribute# 6

In [13]:
a.dtype

dtype('int32')

Attribute# 7

In [16]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

Attribute#8: The function zeros creates an array full of zeros

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Attribute#9: the function ones creates an array full of ones

In [25]:
np.ones((3,4), dtype = np.int16)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

Attribute#10: the function empty creates an array whose initial content is random and depends on the state of the memory

In [29]:
np.empty((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.23709585e-321],
       [2.22525890e-307, 6.23053614e-307, 8.45603441e-307]])

Attribute#11: To create sequences of numbers, NumPy provides the arange function

In [30]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

Attribute#12: Linspapce

In [32]:
from numpy import pi
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

Attribute#13: Print 1d array

In [33]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


Attribute#14: Printing 2d array

In [34]:
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Attribute#15: Printing 3d array

In [35]:
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


Attribute#16: Arithmetic Operations

In [39]:
a = np.array([20,30,40,50])
b = np.arange(4)
c = a - b
print(c)

[20 29 38 47]


Attribute17: Arithmetic Operation 2

In [40]:
d = a * b
print(d)

[  0  30  80 150]


Attribute18: Arithmetic Operations 3

In [41]:
e = b**2
print(e)

[0 1 4 9]


Attribute19: Arithmetic Operations 4

In [43]:
a = np.array([[2, 3],[4, 2]])
b = np.array([[2, 0],[3, 4]])
a @ b

array([[13, 12],
       [14,  8]])

Attribute20: Arithmetic Operation 5

In [45]:
a.dot(b)

array([[13, 12],
       [14,  8]])

Attribute21: Aritmetic Operations 6

In [69]:
a = np.ones((2, 3), dtype= np.int)
a

array([[1, 1, 1],
       [1, 1, 1]])

In [70]:
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

Attribute22: Arithmetic Operations 7

In [71]:
a += 2
a

array([[5, 5, 5],
       [5, 5, 5]])

Attribute#23: Unray Operations 1

In [78]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
a.sum()

66

Attribute#24: Unray Operations 2

In [80]:
a.min()

0

Attribute#25: Unray Operations 3

In [81]:
a.max()

11

Attribute#26: Unray Operations 4

In [82]:
a.sum(axis=0)

array([12, 15, 18, 21])

Attribute#27: Unray Operations 5

In [83]:
a.max(axis=0)

array([ 8,  9, 10, 11])

Attribute#28: Unray Operations 5

In [84]:
a.min(axis=1)

array([0, 4, 8])

Attribute#29: Unray Operations 6

In [85]:
a.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]], dtype=int32)

Attribute#30: Universal Function

In [86]:
a = np.arange(3)
a
np.exp(a)

array([1.        , 2.71828183, 7.3890561 ])

Attribute#31: Universal Function 2

In [87]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356])

Attribute#32: Universal Function 3

In [88]:
np.min(a)

0

Attribute#33: Universal Function 4

In [89]:
b = np.array([1, -1, 2])
np.add(a,b)

array([1, 0, 4])

Attribute#34: Universal Function 5

In [90]:
np.nonzero(a)

(array([1, 2], dtype=int64),)

Attribute#35: Universal Function 6

In [91]:
np.average(a)

1.0

Attribute#36: Universal Function 7

In [94]:
np.sum(a)

3

Attribute#37: Indexing, Slicing, Iterating 1

In [98]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [99]:
a[2]

8

Attribute#38: Indexing, Slicing, Iterating 2

In [100]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

Attribute#39: Indexing, Slicing, Iterating 3

In [105]:
a[:8:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125, 1000,  343,  512,  729],
      dtype=int32)

Attribute#40: Indexing, Slicing, Iterating 4

In [107]:
a[::-1]

array([ 729,  512,  343, 1000,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

Attribute#41: Indexing, Slicing, Iterating 5

In [108]:
for i in a:
    print(i**(1/3))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
5.0
9.999999999999998
6.999999999999999
7.999999999999999
8.999999999999998


Attribute#42: Indexing, Slicing, Iterating 6

In [110]:
def f(x, y):
    return 10 * x + y

b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [111]:
b[2, 3]

23

Attribute#43: Indexing, Slicing, Iterating 7

In [116]:
b[0:5, 2]

array([ 2, 12, 22, 32, 42])

Attribute#44: Indexing, Slicing, Iterating 8

In [119]:
b[1: 4, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33]])

Attribute#45: Shape 1

In [123]:
a = np.floor(10 * rg.random((3, 4)))
a

array([[9., 7., 5., 2.],
       [1., 9., 5., 1.],
       [6., 7., 6., 9.]])

In [124]:
a.ravel()

array([9., 7., 5., 2., 1., 9., 5., 1., 6., 7., 6., 9.])

Attribute#46: Shape 2

In [125]:
a.reshape(6,2)

array([[9., 7.],
       [5., 2.],
       [1., 9.],
       [5., 1.],
       [6., 7.],
       [6., 9.]])

Attribute#47: Shape 3

In [126]:
a.T

array([[9., 1., 6.],
       [7., 9., 7.],
       [5., 5., 6.],
       [2., 1., 9.]])

Attribute#48: Shape 4

In [127]:
a.T.shape

(4, 3)

Attribute#49: Shape 5

In [128]:
a.shape

(3, 4)

Attribute#50: Shape 6

In [132]:
a

array([[9., 7., 5., 2., 1., 9.],
       [5., 1., 6., 7., 6., 9.]])

In [134]:
a.resize((3,4))
a

array([[9., 7., 5., 2.],
       [1., 9., 5., 1.],
       [6., 7., 6., 9.]])